const { createClient } = window.supabase;
const db = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

const departments=["Washing","Dyeing","Printing","Maintenance","ETP","Boiler","Housekeeping","Fabric Washing","Yarn Dyeing","Embroidery","Cutting","Sewing","Packing","Other"];
let currentUser=null,currentProfile=null,chemicals=[],consumptionLogs=[],editingId=null,pendingAction=null,realtimeChannel=null;

const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg,type="success"){const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=msg;$("toastHost").appendChild(el);setTimeout(()=>el.remove(),3500)}
function isAdmin(){return currentProfile?.role==="ADMIN"}
function setSync(on=true){$("syncStatus").innerHTML=`<i></i> ${on?"Synced":"Updating…"}`}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id)?.classList.add("active");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===id));const titles={dashboard:"Dashboard",inventory:"Chemical Inventory",addChemical:"Add Chemical",consumption:"Consumption",reports:"Reports"};$("pageTitle").textContent=titles[id]||"RK-CMS";$("sidebar").classList.remove("open");$("mobileOverlay").classList.remove("show");if(id==="dashboard")renderDashboard();if(id==="inventory")renderInventory();if(id==="consumption"){renderConsumption();populateConsumption();}if(id==="reports")renderReports()}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b){if(b.classList.contains("admin-only")&&!isAdmin())return toast("Administrator access required","error");showPage(b.dataset.page)}const close=e.target.closest("[data-close]");if(close)$(close.dataset.close).classList.add("hidden")});
$("mobileMenuBtn").onclick=()=>{$("sidebar").classList.add("open");$("mobileOverlay").classList.add("show")};$("mobileOverlay").onclick=()=>{$("sidebar").classList.remove("open");$("mobileOverlay").classList.remove("show")};
$("togglePassword").onclick=()=>{const i=$("loginPassword");i.type=i.type==="password"?"text":"password";$("togglePassword").textContent=i.type==="password"?"Show":"Hide"};
function fillSelects(){const opts=departments.map(x=>`<option>${esc(x)}</option>`).join("");$("department").innerHTML='<option value="">Select department</option>'+opts;$("consumptionDepartment").innerHTML='<option value="">Select department</option>'+opts;$("departmentFilter").innerHTML='<option value="">All departments</option>'+opts}
async function loadProfile(){const {data,error}=await db.from("profiles").select("*").eq("id",currentUser.id).single();if(error)throw error;currentProfile={...data,role:String(data.role||"USER").trim().toUpperCase()};$("userName").textContent=data.full_name||currentUser.email.split("@")[0];$("userRole").textContent=currentProfile.role;$("dashName").textContent=data.full_name?.split(" ")[0]||"there";$("avatar").textContent=(data.full_name||currentUser.email).trim().charAt(0).toUpperCase();document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",!isAdmin()))}
async function loadData(){setSync(false);const [c,l]=await Promise.all([db.from("chemicals").select("*").eq("active",true).order("created_at",{ascending:false}),db.from("consumption_logs").select("*").order("consumption_date",{ascending:false}).order("created_at",{ascending:false}).limit(200)]);if(c.error)throw c.error;if(l.error)throw l.error;chemicals=c.data||[];consumptionLogs=l.data||[];setSync(true);renderDashboard();renderInventory();renderConsumption();renderReports()}
function setupRealtime(){if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=db.channel("rkcms-live").on("postgres_changes",{event:"*",schema:"public",table:"chemicals"},async()=>{await loadData();toast("Inventory updated","success")}).on("postgres_changes",{event:"*",schema:"public",table:"consumption_logs"},async()=>{await loadData()}).subscribe()}
function expiryState(date){if(!date)return {text:"No date",cls:"info"};const d=new Date(date+"T23:59:59"),now=new Date(),days=Math.ceil((d-now)/86400000);if(days<0)return{text:"Expired",cls:"danger"};if(days<=30)return{text:`${days}d`,cls:"warn"};return{text:"OK",cls:"ok"}}
function sdsOK(c){return !!(c.sds_path||c.sds_available===true)}
function renderDashboard(){const active=chemicals;const stock=active.filter(c=>Number(c.stock)>0).length;const exp=active.filter(c=>{const d=expiryState(c.expiry_date);return d.cls==="danger"||d.cls==="warn"}).length;const missing=active.filter(c=>!sdsOK(c)).length;$("totalChemicals").textContent=active.length;$("stockChemicals").textContent=stock;$("expiryChemicals").textContent=exp;$("missingSds").textContent=missing;const pct=(n,d)=>d?Math.round(n/d*100):0;const s=pct(active.length-missing,active.length),g=pct(active.filter(c=>String(c.ghs_available).toLowerCase()==="true"||String(c.ghs_available).toLowerCase()==="yes").length,active.length),st=pct(stock,active.length);$("sdsPct").textContent=s+"%";$("sdsBar").style.width=s+"%";$("ghsPct").textContent=g+"%";$("ghsBar").style.width=g+"%";$("stockPct").textContent=st+"%";$("stockBar").style.width=st+"%";$("recentTable").innerHTML=active.slice(0,7).map(c=>`<tr><td class="code">${esc(c.chemical_code)}</td><td><span class="chem-name">${esc(c.chemical_name)}</span><span class="sub">${esc(c.supplier||"No supplier")}</span></td><td>${esc(c.department)}</td><td>${money(c.stock)} ${esc(c.unit||"")}</td><td><span class="badge ${sdsOK(c)?"ok":"danger"}">${sdsOK(c)?"Available":"Missing"}</span></td><td><span class="badge ${expiryState(c.expiry_date).cls}">${expiryState(c.expiry_date).text}</span></td></tr>`).join("")||`<tr><td colspan="6" class="empty">No chemicals found.</td></tr>`}
function filteredChemicals(){const q=$("searchChemical").value.trim().toLowerCase(),d=$("departmentFilter").value,h=$("hazardFilter").value,s=$("sdsFilter").value;return chemicals.filter(c=>(!q||[c.chemical_name,c.chemical_code,c.cas_no,c.supplier].some(v=>String(v||"").toLowerCase().includes(q)))&&(!d||c.department===d)&&(!h||c.hazard===h)&&(!s||(s==="yes"?sdsOK(c):!sdsOK(c))))}
function renderInventory(){const rows=filteredChemicals();$("inventoryTable").innerHTML=rows.map(c=>{const ex=expiryState(c.expiry_date);return `<tr><td class="code">${esc(c.chemical_code)}</td><td><span class="chem-name">${esc(c.chemical_name)}</span><span class="sub">${esc(c.cas_no||"CAS not recorded")}</span></td><td><span class="badge ${c.hazard==="Non-Hazardous"?"ok":"warn"}">${esc(c.hazard)}</span></td><td>${esc(c.department)}</td><td><b>${money(c.stock)}</b> ${esc(c.unit)}</td><td>${esc(c.storage_location||"—")}</td><td><span class="badge ${ex.cls}">${esc(ex.text)}</span><span class="sub">${esc(c.expiry_date||"Not set")}</span></td><td><span class="badge ${sdsOK(c)?"ok":"danger"}">${sdsOK(c)?"PDF / File":"Missing"}</span></td><td><div class="row-actions"><button class="mini-btn" onclick="viewChemical('${esc(c.id)}')">View</button>${isAdmin()?`<button class="mini-btn" onclick="editChemical('${esc(c.id)}')">Edit</button><button class="mini-btn danger" onclick="askDelete('${esc(c.id)}')">Delete</button>`:""}</div></td></tr>`}).join("")||`<tr><td colspan="9" class="empty">No matching chemical records.</td></tr>`}
function populateConsumption(){const s=$("consumptionChemical");s.innerHTML='<option value="">Select chemical</option>'+chemicals.map(c=>`<option value="${c.id}">${esc(c.chemical_code)} — ${esc(c.chemical_name)} (${money(c.stock)} ${esc(c.unit)})</option>`).join("")}
$("consumptionChemical").onchange=()=>{const c=chemicals.find(x=>x.id===$("consumptionChemical").value);$("consumptionUnit").value=c?.unit||""}
function renderConsumption(){const map=new Map(chemicals.map(c=>[c.id,c]));$("consumptionTable").innerHTML=consumptionLogs.slice(0,100).map(l=>{const c=map.get(l.chemical_id);return `<tr><td>${esc(l.consumption_date)}</td><td><b>${esc(c?.chemical_name||l.chemical_name||"Deleted chemical")}</b><span class="sub">${esc(c?.chemical_code||"")}</span></td><td>${esc(l.department||"")}</td><td><b>${money(l.quantity)}</b> ${esc(l.unit||"")}</td><td>${esc(l.used_by||"—")}</td><td>${esc(l.purpose||"—")}</td><td class="code">${esc(l.recorded_by||"—")}</td></tr>`}).join("")||`<tr><td colspan="7" class="empty">No consumption records.</td></tr>`}
function renderReports(){const n=chemicals.length,s=chemicals.filter(sdsOK).length,g=chemicals.filter(c=>String(c.ghs_available).toLowerCase()==="true"||String(c.ghs_available).toLowerCase()==="yes").length,e=chemicals.filter(c=>{const x=expiryState(c.expiry_date);return x.cls==="warn"||x.cls==="danger"}).length;$("sdsAvailable").textContent=s;$("sdsMissing").textContent=n-s;$("ghsMissing").textContent=n-g;$("reportExpiry").textContent=e;const pct=(x)=>n?Math.round(x/n*100):0;$("checkSds").textContent=pct(s)+"%";$("checkGhs").textContent=pct(g)+"%";$("checkStock").textContent=pct(chemicals.filter(c=>Number(c.stock)>=0).length)+"%";$("checkExpiry").textContent=e?`${e} need review`:"OK"} 
async function getSdsUrl(path){if(!path)return null;const {data,error}=await db.storage.from("sds").createSignedUrl(path,600);if(error)throw error;return data.signedUrl}
async function viewChemical(id){const c=chemicals.find(x=>x.id===id);if(!c)return;let url=null;if(c.sds_path){try{url=await getSdsUrl(c.sds_path)}catch(e){console.error(e)}}$("chemicalDetail").innerHTML=`<div class="detail-head"><div><span class="eyebrow">${esc(c.chemical_code)}</span><h2>${esc(c.chemical_name)}</h2><p>${esc(c.supplier||"Supplier not recorded")} • ${esc(c.cas_no||"CAS not recorded")}</p></div><span class="badge ${c.hazard==="Non-Hazardous"?"ok":"warn"}">${esc(c.hazard)}</span></div><div class="detail-grid">${[["Department",c.department],["Stock",`${money(c.stock)} ${c.unit||""}`],["Storage",c.storage_location||"—"],["Purchase date",c.purchase_date||"—"],["Expiry / review",c.expiry_date||"—"],["GHS label",String(c.ghs_available)],["Created",c.created_at?new Date(c.created_at).toLocaleString():"—"],["Remarks",c.remarks||"—"]].map(([a,b])=>`<div class="detail-item"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join("")}</div><div class="detail-sds"><b>SDS document</b><p>${c.sds_path?`<span>${esc(c.sds_file_name||"SDS file")}</span> <a class="primary-btn" style="display:inline-block;padding:7px 10px;margin-left:8px;text-decoration:none" target="_blank" href="${esc(url||"#")}">Open SDS</a>`:`<span class="badge danger">No SDS attached</span>`}</p></div>`;$("chemicalModal").classList.remove("hidden")}
window.viewChemical=viewChemical;
function resetForm(){editingId=null;$("chemicalForm").reset();$("chemicalId").value="";$("formTitle").textContent="Add Chemical";$("saveChemicalBtn").textContent="Save chemical";$("currentSds").classList.add("hidden");$("sdsFileLabel").textContent="Choose SDS file";$("chemicalFormError").textContent=""}
window.editChemical=async id=>{if(!isAdmin())return toast("Administrator access required","error");const c=chemicals.find(x=>x.id===id);if(!c)return;editingId=id;$("formTitle").textContent="Edit Chemical";$("saveChemicalBtn").textContent="Save changes";$("chemicalId").value=id;for(const [id2,val] of [["chemicalName",c.chemical_name],["casNumber",c.cas_no],["supplier",c.supplier],["department",c.department],["hazard",c.hazard],["stock",c.stock],["unit",c.unit],["storage",c.storage_location],["purchaseDate",c.purchase_date],["expiryDate",c.expiry_date],["ghs",String(c.ghs_available).toLowerCase()==="true"?"Yes":"No"],["remarks",c.remarks]]){if($(id2))$(id2).value=val??""}if(c.sds_path){$("currentSds").innerHTML=`Current SDS: <b>${esc(c.sds_file_name||c.sds_path)}</b>`;$("currentSds").classList.remove("hidden")}showPage("addChemical")}; 
window.askDelete=id=>{if(!isAdmin())return;const c=chemicals.find(x=>x.id===id);pendingAction=async()=>{const {data,error}=await db.rpc("delete_chemical_admin",{p_chemical_id:id});if(error)throw error;if(!data?.deleted){const ok=confirm((data?.message||"This record cannot be permanently deleted.")+"\n\nArchive it instead?");if(ok){const r=await db.rpc("archive_chemical_admin",{p_chemical_id:id});if(r.error)throw r.error;if(!r.data?.archived)throw new Error(r.data?.message||"Unable to archive.");toast("Chemical archived");await loadData()}return}if(c?.sds_path)await db.storage.from("sds").remove([c.sds_path]);toast("Chemical deleted successfully");await loadData()};$("confirmTitle").textContent="Delete chemical?";$("confirmText").textContent=`Delete ${c?.chemical_name||"this chemical"} permanently? Records with consumption history will be protected and can be archived.`;$("confirmModal").classList.remove("hidden")};
$("confirmAction").onclick=async()=>{if(!pendingAction)return;$("confirmModal").classList.add("hidden");try{await pendingAction()}catch(e){console.error(e);toast(e.message||"Action failed","error")}finally{pendingAction=null}};
$("sdsFile").onchange=()=>{const f=$("sdsFile").files[0];if(f){if(f.size>10*1024*1024){$("sdsFile").value="";return toast("SDS file must be 10 MB or smaller","error")}$("sdsFileLabel").textContent=f.name}}
async function uploadSds(file,chemicalId){if(!file)return null;const ext=(file.name.split(".").pop()||"pdf").toLowerCase();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${chemicalId}/${crypto.randomUUID()}_${safe}`;const {error}=await db.storage.from("sds").upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;return {path,name:file.name,ext}}
$("chemicalForm").onsubmit=async e=>{e.preventDefault();if(!isAdmin())return toast("Administrator access required","error");$("chemicalFormError").textContent="";$("saveChemicalBtn").disabled=true;try{const file=$("sdsFile").files[0];const payload={chemical_name:$("chemicalName").value.trim(),cas_no:$("casNumber").value.trim(),supplier:$("supplier").value.trim(),department:$("department").value,hazard:$("hazard").value,stock:Number($("stock").value)||0,unit:$("unit").value,storage_location:$("storage").value.trim(),purchase_date:$("purchaseDate").value||null,expiry_date:$("expiryDate").value||null,ghs_available:$("ghs").value==="Yes",remarks:$("remarks").value.trim(),updated_by:currentUser.id};let id=editingId;if(editingId){const {data,error}=await db.from("chemicals").update(payload).eq("id",editingId).select().single();if(error)throw error}else{payload.created_by=currentUser.id;payload.chemical_code=`CH-${Date.now().toString().slice(-6)}`;const {data,error}=await db.from("chemicals").insert(payload).select().single();if(error)throw error;id=data.id}if(file){const up=await uploadSds(file,id);const {error}=await db.from("chemicals").update({sds_path:up.path,sds_file_name:up.name,sds_available:true,sds_uploaded_at:new Date().toISOString(),updated_by:currentUser.id}).eq("id",id);if(error)throw error}toast(editingId?"Chemical updated":"Chemical added");resetForm();await loadData();showPage("inventory")}catch(e){console.error(e);$("chemicalFormError").textContent=e.message||"Unable to save chemical"}finally{$("saveChemicalBtn").disabled=false}};
$("clearForm").onclick=resetForm;
$("consumptionForm").onsubmit=async e=>{e.preventDefault();$("consumptionError").textContent="";const chemicalId=$("consumptionChemical").value,qty=Number($("consumptionQty").value);if(!chemicalId||qty<=0)return;$("consumptionForm").querySelector("button[type=submit]").disabled=true;try{const {data,error}=await db.rpc("record_consumption",{p_chemical_id:chemicalId,p_quantity:qty,p_unit:$("consumptionUnit").value,p_date:$("consumptionDate").value,p_department:$("consumptionDepartment").value,p_used_by:$("consumptionUser").value.trim(),p_purpose:$("consumptionPurpose").value.trim(),p_remarks:$("consumptionRemarks").value.trim()});if(error)throw error;if(!data?.success)throw new Error(data?.message||"Unable to record consumption");toast("Consumption recorded and stock updated");$("consumptionForm").reset();$("consumptionDate").value=today();$("consumptionUnit").value="";await loadData()}catch(e){console.error(e);$("consumptionError").textContent=e.message||"Unable to save consumption"}finally{$("consumptionForm").querySelector("button[type=submit]").disabled=false}};
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`}function downloadCSV(name,headers,rows){const csv=[headers,...rows].map(r=>r.map(csvCell).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("exportInventory").onclick=()=>downloadCSV("RK-CMS_Chemical_Inventory.csv",["Code","Chemical","CAS","Supplier","Department","Hazard","Stock","Unit","Storage","Purchase Date","Expiry","SDS","GHS","Remarks"],chemicals.map(c=>[c.chemical_code,c.chemical_name,c.cas_no,c.supplier,c.department,c.hazard,c.stock,c.unit,c.storage_location,c.purchase_date,c.expiry_date,sdsOK(c)?"Yes":"No",c.ghs_available?"Yes":"No",c.remarks]));
$("exportConsumption").onclick=()=>{const map=new Map(chemicals.map(c=>[c.id,c]));downloadCSV("RK-CMS_Consumption.csv",["Date","Chemical","Code","Department","Quantity","Unit","Used By","Purpose","Remarks"],consumptionLogs.map(l=>{const c=map.get(l.chemical_id);return[l.consumption_date,c?.chemical_name,l.chemical_code,l?.department,l.quantity,l.unit,l.used_by,l.purpose,l.remarks]}))}
$("exportAll").onclick=()=>{const rows=chemicals.map(c=>[c.chemical_code,c.chemical_name,c.department,c.hazard,c.stock,c.unit,sdsOK(c)?"Available":"Missing",c.ghs_available?"Available":"Missing",expiryState(c.expiry_date).text,c.expiry_date]);downloadCSV("RK-CMS_Compliance_Report.csv",["Code","Chemical","Department","Hazard","Stock","Unit","SDS","GHS","Expiry Status","Expiry Date"],rows)}
$("refreshBtn").onclick=async()=>{try{await loadData();toast("Data refreshed")}catch(e){toast(e.message,"error")}}
["searchChemical","departmentFilter","hazardFilter","sdsFilter"].forEach(id=>$(id).addEventListener("input",renderInventory));
$("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()};
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";$("loginBtn").disabled=true;try{const {error}=await db.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)throw error}catch(err){$("loginError").textContent=err.message||"Sign in failed"}finally{$("loginBtn").disabled=false}};
async function start(){fillSelects();$("consumptionDate").value=today();const {data:{session}}=await db.auth.getSession();if(!session)return;$("loginPage").classList.add("hidden");$("appShell").classList.remove("hidden");currentUser=session.user;try{await loadProfile();await loadData();setupRealtime();showPage("dashboard")}catch(e){console.error(e);toast("Account setup error: "+e.message,"error");await db.auth.signOut();$("loginPage").classList.remove("hidden");$("appShell").classList.add("hidden")}}
db.auth.onAuthStateChange((_event,session)=>{if(session&&!currentUser){currentUser=session.user;start()}});
start();
